#!/bin/sh
set -e

case "$1" in
	remove)
	;;

	purge)
		rm -rf /var/lib/elasticsearch /var/log/elasticsearch
		deluser elasticsearch || true
		delgroup elasticsearch || true
	;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
		echo "$0 called with unknown argument \`$1'" >&2
		exit 1
	;;
esac
