#!/bin/sh
set -e

case "$1" in
	remove)
		# --[ First stop service ]
		[ -x /usr/sbin/invoke-rc.d ] && /usr/sbin/invoke-rc.d elasticsearch stop
		[ -x /sbin/service ] && /sbin/service elasticsearch stop

		# --[ Then remove service ]--
		[ -x /sbin/insserv ] && /sbin/insserv -r elasticsearch
		[ -x /sbin/chkconfig ] && /sbin/chkconfig -del elasticsearch > /dev/null
		
	;;

	purge)
		rm -rf /var/lib/elasticsearch /var/log/elasticsearch
		deluser elasticsearch || true
		delgroup elasticsearch || true
	;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
		echo "$0 called with unknown argument \`$1'" >&2
		exit 1
	;;
esac
